SELECT (CASE WHEN ((SELECT SUM(CODE) FRONT FROM SKILLCODES WHERE CATEGORY='Front End') & SKILL_CODE>0) AND ((SELECT CODE FROM SKILLCODES WHERE NAME='Python') & SKILL_CODE>0) THEN 'A'
            WHEN (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME='C#') > 0) THEN 'B'
            ELSE 'C' END) GRADE, ID, EMAIL
FROM DEVELOPERS
ORDER BY GRADE, ID