-- HAVING 사용
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) >= 2
ORDER BY USER_ID, PRODUCT_ID DESC

-- WHERE 조건
SELECT DISTINCT o1.USER_ID, o2.PRODUCT_ID	
FROM ONLINE_SALE o1, ONLINE_SALE o2
WHERE o1.USER_ID = o2.USER_ID 
    AND o1.PRODUCT_ID = o2.PRODUCT_ID 
    AND o1.SALES_DATE != o2.SALES_DATE
ORDER BY 1, 2 DESC;

/* 중복값 제거: DISTINCT
 논리 연산자 처럼, 재구매 상품 조회하는 방법 익히기 
 */