SELECT SCORE, HR_EMPLOYEES.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES, (SELECT EMP_NO, YEAR, SUM(SCORE) SCORE
                    FROM HR_GRADE
                    WHERE YEAR=2022
                    GROUP BY EMP_NO
                    ORDER BY SCORE DESC
                    LIMIT 1) A
WHERE HR_EMPLOYEES.EMP_NO = A.EMP_NO