SELECT FLAVOR, TOTALA+TOTALB
FROM (SELECT A.SHIPMENT_ID, A.FLAVOR, SUM(A.TOTAL_ORDER) AS TOTALA, SUM(B.TOTAL_ORDER) AS TOTALB
    FROM FIRST_HALF A LEFT JOIN JULY B ON A.SHIPMENT_ID = B.SHIPMENT_ID
    GROUP BY A.FLAVOR
    UNION
    SELECT A.SHIPMENT_ID, A.FLAVOR, SUM(A.TOTAL_ORDER) AS TOTALA, SUM(B.TOTAL_ORDER) AS TOTALB
    FROM FIRST_HALF A RIGHT JOIN JULY B ON A.SHIPMENT_ID = B.SHIPMENT_ID
    GROUP BY B.FLAVOR) C
ORDER BY TOTALA + TOTALB DESC