SELECT HISTORY_ID, (CASE WHEN DATEDIFF(END_DATE, START_DATE)+1 BETWEEN 7 AND 29
                    THEN ROUND((SELECT (100-DISCOUNT_RATE) * 0.01  FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE LIKE '7%' AND CAR_TYPE = '트럭') * DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1))
                    WHEN DATEDIFF(END_DATE, START_DATE)+1 BETWEEN 30 AND 89
                    THEN ROUND((SELECT (100-DISCOUNT_RATE) * 0.01 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE LIKE '30%' AND CAR_TYPE = '트럭') * DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1))
                    WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90
                    THEN ROUND((SELECT (100-DISCOUNT_RATE) * 0.01 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE LIKE '90%' AND CAR_TYPE = '트럭') * DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1))
                    ELSE DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1) END) FEE
FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC