WITH RECURSIVE G AS (
    SELECT ID, PARENT_ID, 1 GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT GG.ID, GG.PARENT_ID, G.GENERATION+1
    FROM G, ECOLI_DATA GG
    WHERE G.ID = GG.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM G
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM G WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION