SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT USER_ID) AS PUCHASED_USERS, 
        ROUND((COUNT(DISTINCT USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021)),1) AS PUCHASED_RATIO
FROM (SELECT A.USER_ID, A.JOINED, B.SALES_DATE
    FROM USER_INFO A, ONLINE_SALE B
    WHERE A.USER_ID = B.USER_ID AND YEAR(JOINED) = 2021) A
GROUP BY YEAR, MONTH