SELECT CAR_ID, C.CAR_TYPE, ROUND((DAILY_FEE*((100-DISCOUNT_RATE)/100))*30) AS FEE
FROM (
    SELECT DISTINCT A.CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    WHERE A.CAR_ID = B.CAR_ID AND CAR_TYPE IN ('세단','SUV') AND A.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE END_DATE>='2022-11-01' AND START_DATE<'2022-12-01')) C, CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
WHERE C.CAR_TYPE = D.CAR_TYPE AND DURATION_TYPE = '30일 이상' AND (ROUND((DAILY_FEE*((100-DISCOUNT_RATE)/100))*30 BETWEEN 500000 AND 2000000))
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC